name: Local Build & Restart (Self-hosted)
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-restart:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & (re)start with Compose
        run: |
          docker compose pull || true
          docker compose build --no-cache
          docker compose up -d