name: Local Build & Restart (Self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-restart:
    runs-on: self-hosted
    env:
      DB_CONN: ${{ secrets.DB_CONN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LOVENSE_TOKEN: ${{ secrets.LOVENSE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve compose path
        id: paths
        shell: bash
        run: |
          set -euo pipefail
          # hard-code the path you verified:
          COMPOSE="/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml"
          test -f "$COMPOSE" || { echo "::error::compose file not found at $COMPOSE"; exit 1; }
          echo "compose=$COMPOSE" >> "$GITHUB_OUTPUT"
          echo "projectdir=$(dirname "$COMPOSE")" >> "$GITHUB_OUTPUT"

      - name: Sanity check (show file & env that can break compose)
        shell: bash
        run: |
          set -x
          id && whoami
          ls -l "${{ steps.paths.outputs.compose }}"
          head -n 20 "${{ steps.paths.outputs.compose }}"
          env | grep -E '^(COMPOSE|DOCKER)_' || true

      - name: Validate with Compose v2
        shell: bash
        run: |
          # neutralize env overrides that can cause "no configuration file provided"
          unset COMPOSE_FILE COMPOSE_PATH_SEPARATOR COMPOSE_PROFILES COMPOSE_PROJECT_NAME
          docker compose \
            --project-directory "${{ steps.paths.outputs.projectdir }}" \
            -f "${{ steps.paths.outputs.compose }}" \
            config > /dev/null

      - name: Build images (v2)
        shell: bash
        run: |
          unset COMPOSE_FILE COMPOSE_PATH_SEPARATOR COMPOSE_PROFILES COMPOSE_PROJECT_NAME
          docker compose \
            --project-directory "${{ steps.paths.outputs.projectdir }}" \
            -f "${{ steps.paths.outputs.compose }}" \
            build

      - name: Start/Restart containers (v2)
        shell: bash
        run: |
          unset COMPOSE_FILE COMPOSE_PATH_SEPARATOR COMPOSE_PROFILES COMPOSE_PROJECT_NAME
          docker compose \
            --project-directory "${{ steps.paths.outputs.projectdir }}" \
            -f "${{ steps.paths.outputs.compose }}" \
            up -d --remove-orphans