name: Local Build & Restart (Self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-restart:
    runs-on: self-hosted
    env:
      DB_CONN: ${{ secrets.DB_CONN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LOVENSE_TOKEN: ${{ secrets.LOVENSE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show compose env & file
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          env | grep -E '^(COMPOSE|DOCKER)_' || true
          ls -l "/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml"
          head -n 20 "/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml"

      - name: Validate compose file (config)
        shell: bash
        run: |
          docker compose -f "/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml" config > /dev/null

      - name: Build images
        shell: bash
        run: |
          docker compose -f "/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml" build

      - name: Start/Restart containers
        shell: bash
        run: |
          docker compose -f "/opt/actions-runner/teasybot/_work/TeasyBot/TeasyBot/docker-compose.yml" up -d --remove-orphans