name: Local Build & Restart (Self-hosted)

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ${{ github.workspace }}

jobs:
  build-and-restart:
    runs-on: self-hosted
    env:
      DB_CONN: ${{ secrets.DB_CONN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LOVENSE_TOKEN: ${{ secrets.LOVENSE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check path
        run: |
          pwd
          ls -la

      - name: Build images
        run: docker compose build

      - name: Start/Restart containers
        run: docker compose up -d --remove-orphans