name: Local Build & Restart (Self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-restart:
    runs-on: self-hosted
    env:
      DB_CONN: ${{ secrets.DB_CONN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LOVENSE_TOKEN: ${{ secrets.LOVENSE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check workspace & compose
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la "$GITHUB_WORKSPACE"
          echo "Compose candidates:"
          find "$GITHUB_WORKSPACE" -maxdepth 2 \( -iname 'docker-compose.y*ml' -o -iname 'compose.y*ml' \) -print
          echo "Docker/Compose versions:"
          docker --version || true
          docker compose version || true

      - name: Resolve compose file path
        id: compose
        shell: bash
        run: |
          set -euo pipefail
          # Prefer docker-compose.yml, then docker-compose.yaml, then compose.yml/.yaml
          for f in \
            "$GITHUB_WORKSPACE/docker-compose.yml" \
            "$GITHUB_WORKSPACE/docker-compose.yaml" \
            "$GITHUB_WORKSPACE/compose.yml" \
            "$GITHUB_WORKSPACE/compose.yaml"
          do
            if [[ -f "$f" ]]; then
              echo "file=$f" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "::error::No compose file found in $GITHUB_WORKSPACE (looked for docker-compose.yml/.yaml or compose.yml/.yaml)"
          exit 1

      - name: Validate compose file
        shell: bash
        run: docker compose -f "${{ steps.compose.outputs.file }}" config > /dev/null

      - name: Build images
        shell: bash
        run: docker compose -f "${{ steps.compose.outputs.file }}" build

      - name: Start/Restart containers
        shell: bash
        run: docker compose -f "${{ steps.compose.outputs.file }}" up -d --remove-orphans